site_name: appname
site_description: Its all about a Weissman score > 5.0
repo_url: https://github.com/milosh012/tttt
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/milosh012">milosh012</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
